### ISSUE TITLE
Missing licence

### ISSUE THREAD

**Issue by sergiubologa** [denniske/ngx-translate-multi-http-loader#11]
Hello @denniske,

I'd like to ask about licensing for this plugin, why is it missing? If there's no license it's not really open source and we can't use it in enterprise software.

Thanks in advance.

**Comment by denniske** [comment]
Hi, no problem. I have added a license now: https://github.com/denniske/ngx-translate-multi-http-loader/blob/master/LICENSE

**Comment by sergiubologa** [comment]
Thanks! Greatly appreciated!

**Comment by anatolie-darii** [comment]
@denniske 
Could you maybe cut a new tag as well? 
I see the license is added but the latest version on npmjs is still 7.0.2 without the license.
Thanks!

**Comment by denniske** [comment]
@anatolie-darii Sure, I have published 7.0.3.

**Comment by anatolie-darii** [comment]
@denniske although everything seems in order code wise, looks like npmjs still reports the package as having no license :(
![image](https://user-images.githubusercontent.com/19292346/156554033-f9a7cadd-a42b-4702-b3b3-c1d8a77450ac.png)

**Comment by denniske** [comment]
@anatolie-darii I have added the corresponding field to the package.json in the libs folder. It should be shown on npmjs now.

**Comment by anatolie-darii** [comment]
@denniske Thanks for the prompt response. Works now! 🎉
