### ISSUE TITLE
Angular 15 Module not found: Error: Can't resolve 'deepmerge-ts'

### ISSUE THREAD

**Issue by Rezorl** [denniske/ngx-translate-multi-http-loader#25]
Angular: 15.0.4
@ngx-translate/core: 14.0.0
ngx-translate-multi-http-loader: 9.3.0
typescript: 4.8.4

**ng serve:** 

./node_modules/ngx-translate-multi-http-loader/fesm2020/ngx-translate-multi-http-loader.mjs:2:0-41 - Error: Module not found: Error: Can't resolve 'deepmerge-ts' in 'node_modules\ngx-translate-multi-http-loader\fesm2020'

**package.json:**

  "dependencies": {
    "@angular/animations": "15.0.4",
    "@angular/cdk": "15.0.4",
    "@angular/common": "15.0.4",
    "@angular/compiler": "15.0.4",
    "@angular/core": "15.0.4",
    "@angular/forms": "15.0.4",
    "@angular/material": "15.0.4",
    "@angular/platform-browser": "15.0.4",
    "@angular/platform-browser-dynamic": "15.0.4",
    "@angular/router": "15.0.4",
    "@busacca/ng-pick-datetime": "13.0.1",
    "@ng-select/ng-select": "10.0.3",
    "@ngrx/component-store": "15.1.0",
    "@ngx-translate/core": "14.0.0",
    "annyang": "2.6.1",
    "core-js": "2.6.5",
    "ismobilejs": "1.1.1",
    "lodash-es": "4.17.21",
    "moment": "2.29.1",
    "ngx-translate-multi-http-loader": "9.3.0",
    "rxjs": "~7.8.0",
    "tslib": "2.3.1",
    "zone.js": "~0.11.4"
  }

**Comment by rbalet** [comment]
@Rezorl This is due to some version of npm not being able to download peerDependencies properly.

I let you run `npm i deepmerge-ts`, this should fix the problem.

I decided to not move it under `dependencies` since it's considered to be a bad practice.

Cheers
