### ISSUE TITLE
 ngx-translate-multi-http-loader uses deepmerge-ts package

### ISSUE THREAD

**Issue by poojakumari19** [denniske/ngx-translate-multi-http-loader#26]
ngx-translate-multi-http-loader uses deepmerge-ts package but  deepmerge-ts is not the MIT license so its difficult to use ngx-translate-multi-http- in project .

Can you add dependency of  deepmerge-ts  under  ngx-translate-multi-http-loader

**Comment by rbalet** [comment]
@poojakumari19 For what it worth, the license used by `deepmerge-ts` seems the same.

The only thing is, 
> you should not mention the name of the copyright holder or its contributors to promote derived products without written consent

Or could you explain to me the difference ? 
Then & if it make sense I'll write to the `deepmerge-ts` team to ask them if they can change their license.  

![image](https://user-images.githubusercontent.com/44493964/216379997-d8fd1f84-84c0-4ecf-a9fa-bd04e6dd2971.png)

**Comment by rbalet** [comment]
@poojakumari19 Since I do not have any update from your side, I'm closing this issue.
Feel free to open it again
