### ISSUE TITLE
can't resolve

### ISSUE THREAD

**Issue by itcozum** [denniske/ngx-translate-multi-http-loader#28]
H,
I'm having issue with version 9.3.2 of this component usingAngular 15.2.4, with the below error message

./node_modules/ngx-translate-multi-http-loader/fesm2020/ngx-translate-multi-http-loader.mjs:2:0-41 - Error: Module not found: Error: Can't resolve 'deepmerge-ts' in 'S:\Software\BufferFly\Software\Butterfly.Framework\Butterfly.Portal\WEB\NEW\node_modules\ngx-translate-multi-http-loader\fesm2020'

Please need some help on how to resolve this problem.

Thanks in advance

**Comment by rbalet** [comment]
Close as duplicate ;)

https://github.com/rbalet/ngx-translate-multi-http-loader/issues/25#issuecomment-1378527885
