### ISSUE TITLE
Add support for Angular 16

### ISSUE THREAD

**Issue by shipengqi** [denniske/ngx-translate-multi-http-loader#29]
Hello, Angular 16 has now been released, are there any plans to upgrade?

**Comment by rbalet** [comment]
Hi. 
Yes, but I wont have the time to look at it before the next month. 

Any pr are welcome :)

**Comment by rbalet** [comment]
@shipengqi Done on the latest release https://github.com/rbalet/ngx-translate-multi-http-loader/releases/tag/v15.0.0

I've updated the version from 9 to 15 to sync it with the [@ngx-translate/core](https://github.com/ngx-translate/core) library

Please, don't hesitate to open issues if you face any error
