### ISSUE TITLE
fails to load an entire bundle chain if any json files are missing.

### ISSUE THREAD

**Issue by Deklin** [denniske/ngx-translate-multi-http-loader#3]
## Current behavior
Lets say I have 3 bundles
/assets/bundle1/i18n/en.json
/assets/bundle2/i18n/en.json
/assets/bundle3/i18n/en.json

If Any of those files are missing, all strings fail to load.

## Expected behavior
Log the error for missing entry but don't fail the entire load.

## Minimal reproduction of the problem with instructions
If you use your existing example and just remove one of the en.json files the issue will appear. No strings will appear.

https://stackblitz.com/edit/ngx-translate-multi-http-loader-sample-bhkkcf

You can see all I did was rename one of the JSON files.

## Environment

<pre><code>
ngx-translate version: 11.0.1
ngx-translate-multi-http-loader: 2.1.2
Angular version: 7.2.2

Browser:
- [ x] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 11.1.0
- Platform:  Mac/Linux

Others:

</code></pre>

**Comment by denniske** [comment]
I just fixed this in v3.0.0. Please try out.

**Comment by Deklin** [comment]
@denniske thanks!

**Comment by Deklin** [comment]
@denniske was this published to the npm repo?
