### ISSUE TITLE
TypeError: values.at is not a function

### ISSUE THREAD

**Issue by robin3190** [denniske/ngx-translate-multi-http-loader#30]
Translations are not working rn and i get this Error:

ERROR TypeError: values.at is not a function
    at Object.mergeOthers$2 [as mergeOthers] (index.mjs:200)
    at mergeOthers$1 (index.mjs:366)
    at mergeUnknowns (index.mjs:267)
    at Object.mergeRecords$2 [as mergeRecords] (index.mjs:153)
    at mergeRecords$1 (index.mjs:304)
    at mergeUnknowns (index.mjs:282)
    at customizedDeepmerge (index.mjs:230)
    at deepmerge (index.mjs:220)
    at ngx-translate-multi-http-loader.mjs:28
    at map.js:7

I had the issue number 25 first and the module deepmerge was missing so i added it via ''npm i deepmerge-ts''

here are my versions:
"dependencies": {
        "@angular/animations": "~15.2.9",
        "@angular/cdk": "^15.2.9",
        "@angular/common": "~15.2.9",
        "@angular/compiler": "~15.2.9",
        "@angular/core": "~15.2.9",
        "@angular/forms": "~15.2.9",
        "@angular/material": "^15.2.9",
        "@angular/platform-browser": "~15.2.9",
        "@angular/platform-browser-dynamic": "~15.2.9",
        "@angular/router": "~15.2.9",
        "@apollo/client": "^3.7.14",
        "@ngx-translate/http-loader": "^7.0.0",
        "apexcharts": "^3.40.0",
        "apollo-angular": "^4.2.1",
        "chart.js": "4.2.1",
        "deepmerge-ts": "^5.1.0",
        "graphql": "^16.6.0",
        "graphql-ws": "^5.12.0",
        "mat-table-exporter": "^15.0.0",
        "ng-apexcharts": "1.7.4",
        "ng2-trim-on-blur": "^1.0.7",
        "ngx-timeago": "^2.0.0",
        "ngx-translate-multi-http-loader": "^15.0.0",
        "rxjs": "~7.8.1",
        "tslib": "^2.3.0",
        "xlsx": "^0.18.5",
        "zone.js": "^0.11.8"
    },
    "devDependencies": {
        "@angular-devkit/build-angular": "~15.2.8",
        "@angular/cli": "~15.2.8",
        "@angular/compiler-cli": "~15.2.9",
        "@angular/localize": "^15.2.9",
        "@graphql-codegen/cli": "^3.3.1",
        "@graphql-codegen/near-operation-file-preset": "^2.5.0",
        "@graphql-codegen/typescript": "^3.0.4",
        "@graphql-codegen/typescript-apollo-angular": "^3.5.6",
        "@graphql-codegen/typescript-operations": "^3.0.4",
        "@ngx-translate/core": "^14.0.0",
        "@types/jasmine": "~4.3.1",
        "@types/node": "^18.16.3",
        "@typescript-eslint/eslint-plugin": "^5.59.7",
        "@typescript-eslint/parser": "^5.59.7",
        "eslint": "^8.41.0",
        "jasmine-core": "~4.5.0",
        "karma": "~6.4.1",
        "karma-chrome-launcher": "~3.1.0",
        "karma-coverage": "~2.2.0",
        "karma-jasmine": "~5.1.0",
        "karma-jasmine-html-reporter": "~2.0.0",
        "typescript": "~4.9.5"
    }

> @robin3190 Can you try downloading the following `npm install ngx-translate-multi-http-loader@9.4.0` ? This was the version ready for the angular v15 (As per my Readme)
> 
> The v15 is for the angular v16.
> 
> I see that this does not make a lot of sense so I've update a new version for the 16 named 16.
> 
> _Feel free to reopen the issue in case it didn't fixed your problem, but please let me know, that I update the required dependencies_
> 
> Cheers

This does not solve the Problem

**Comment by rbalet** [comment]
@robin3190  Can you try downloading the following `npm install ngx-translate-multi-http-loader@9.4.0` ? This was the version ready for the angular v15 (As per my Readme)

The v15 is for the angular v16. 

I see that this does not make a lot of sense so I've update a new version for the 16 named 16.

_Feel free to reopen the issue in case it didn't fixed your problem,  but please let me know, that I update the required dependencies_

Cheers

**Comment by jbgtmartin** [comment]
I had the same issue, because `deepmerge-ts@5` uses `Array.at`, which is [not supported](https://caniuse.com/?search=array.at) in (not so) old versions of Safari (< 15.4).

I fixed the issue by including the corresponding polyfill in my app:
- Install `core-js`
- In polyfills.ts, add `import 'core-js/modules/es.array.at';`

**Comment by rbalet** [comment]
> I had the same issue, because `deepmerge-ts@5` uses `Array.at`, which is [not supported](https://caniuse.com/?search=array.at) in (not so) old versions of Safari (< 15.4).
> 
> I fixed the issue by including the corresponding polyfill in my app:
> 
> * Install `core-js`
> * In polyfills.ts, add `import 'core-js/modules/es.array.at';`

Nice, thx a lot for your message.

I'll update the readme in case it helps anybody

**Comment by rbalet** [comment]
@jbgtmartin Here you are : https://github.com/rbalet/ngx-translate-multi-http-loader#valuesat-is-not-a-function
