### ISSUE TITLE
Use with standalone components

### ISSUE THREAD

**Issue by mtabaj** [denniske/ngx-translate-multi-http-loader#32]
Hi, I used this library without problems before, but now I need to use it in a standalone project, with standalone components.
I can't find how to declare it in the standalone component.

I declare it in the app.config : 
```typescript
importProvidersFrom(TranslateModule.forRoot({
      defaultLanguage: 'fr',
      loader: {
        provide: TranslateLoader,
        useFactory: HttpLoaderFactory,
        deps: [HttpBackend],
      },
    })),
```
But in each component I need to declare the files to use.
Can you help me, please ?

**Comment by rbalet** [comment]
Hi there @mtabaj 

It looks to me like you wanted to open this question in the [ngx-translate](https://github.com/ngx-translate/core) library

Or did I missunderstand the question ? 

Closing the issue, feel free to reopen it

**Comment by mtabaj** [comment]
Hi @rbalet,
I think it's inherent to this library.  I don't want to reload ngx-translate, I want just change the json files to load.
But may be I'm wrong...

**Comment by rbalet** [comment]
@mtabaj I'd be stunned about that, but could be worth giving it a look.

Can you please make me a stackblitz or anything that would help me having a reproducible error.
That way I could dig deeper into it. 

Kindly regards

**Comment by rbalet** [comment]
Hi @mtabaj, I'm closing this issue as I do not have had any comment from your side.

Feel free to open it again.

Cheers
