### ISSUE TITLE
Missing missing-translate-handler support

### ISSUE THREAD

**Issue by work933k** [denniske/ngx-translate-multi-http-loader#36]
When running automated tests we check for messages given by our Custom Missing translation handler. This ensures that we won't release applications with translation issues. 

Is it maybe possible to add support for the missingTranslationHandler?

```
 missingTranslationHandler: {
      provide: MissingTranslationHandler,
      useClass: CustomMissingTranslationHandler,
}
```

**Comment by rbalet** [comment]
Hi @work933k, thx for the issue, but I'm closing it, as the `missingTranslationHandler` isn't added in this library, but on an higher level.

Please, reopen the issue if I'm wrong.  
Any PRs are welcome ;)
