### ISSUE TITLE
Does this package support Angular Universal?

### ISSUE THREAD

**Issue by ElesGergo** [denniske/ngx-translate-multi-http-loader#7]
I am getting the following error when I try to serve the app with angular universal.

I have tried many ways to reach the location of the file with http client and it seems that not the route is the problem.

Is that possible that it is not working because of http client on serverside. I have seen other libaries using fs for loading static files on the server side.

Error message:
Could not find translation file: xyz

**Comment by denniske** [comment]
I never tried it with angular universal. I think it should work when ngx-translate works with angular universal. Did you try using ngx-translate with only one translation file and angular universal?

**Comment by ElesGergo** [comment]
I found the solution. So this will not work because with universal you should use the filesystem to read in the translations.

**Comment by denniske** [comment]
Okay so I can close this?

**Comment by ElesGergo** [comment]
Yes, the verdict is that it is not supported currently.Would you accept a pull request with a new module for Angular universal support?

**Comment by denniske** [comment]
You can create a pull request for https://github.com/ngx-translate/http-loader which I forked this repo from. Then I can pull the changes from there.
